MAP = {
    # InDesign generated attributes
    "span[class*=\"CharOverride-\"]": { "name": "span" },
    # "p.ParaOverride-": { "name": "p" },
    # "div[class*=\"_idGenObjectStyleOverride-\"]": { "name": "span" },
    # BOLLO
    "#_idContainer011 p.Courant_01": { "name": "p" },
    "#_idContainer012 p.Courant_01": { "name": "p" },
    "#_idContainer013 p.Courant_01": { "name": "p" },
    "p.Courant_01": { "name": "div", "classes": ["firstParagraph"] },
    "p.Courant_02": { "name": "p" },
    "p.Titre": { "name": "h1" },
    "p.Auteur": { "name": "h2", "classes": ["author"] },
    "p.intertitre": { "name": "h2" },
    "span.Italique": { "name" : "i" },
    "p.Paragraphe-standard": { "name": "p" },
    "div.Bloc-de-texte-standard": { "name": "div" },
    # NN
    "p.h1": { "name": "h1" },
    "p.txt1": { "name": "div", "classes": ["firstParagraph"] },
    "p.Pr-face--avant-propos": { "name": "h1", "classes": ["pretitre"] },
    "p.indent": { "name": "li" },
    "p.h2": { "name": "h2" },
    "p.H2-partie-20": { "name": "h2" },
    "p.h2-0-avant-0-apr-s": { "name": "h2" },
    "span.BBB-it-11-5": { "name": "i" },
    "span.BBB-reg-it-9": { "name": "i" },
    "span.BBB-it-11-5": { "name": "i" },
    "span.Appel-de-note": { "name": "span", "classes": ["fn"] },
    # PLE
    # "div.Bloc-Corps-de-texte": { "name": "", "classes": [] },
    "div.Bloc-bio": {},
    # "div.Bloc-image": { "name": "", "classes": [] },
    # "div.Bloc-titre-auteur": { "name": "", "classes": [] },
    # "div.Corps_de_texte_premi-re_page": { "name": "", "classes": [] },
    "div.Frise": {},
    # "div.L-gende-photo": { "name": "", "classes": [] },
    # "div.Note_droite": { "name": "", "classes": [] },
    # "div.Note_gauche": { "name": "", "classes": [] },
    # "div.Pagis_PucePagis": { "name": "", "classes": [] },
    # "div._idGenObjectLayout-1": { "name": "", "classes": [] },
    "img._idGenObjectAttribute-1": { "name": "img" },
    "img._idGenObjectAttribute-2": { "name": "img" },
    "img._idGenObjectAttribute-3": { "name": "img" },
    "p.Chapitre": { "name": "h3", "classes": ["chapter"] },
    "p.Citation": { "name": "blockquote" },
    "p.Citation-dans-txt-courant": { "name": "blockquote", "classes": ["courant"] },
    "p.Corps-de-texte": { "name": "p" },
    "p.Dialogue": { "name": "blockquote", "classes": ["dialog"] },
    "p.Ent-tes_Titre": {},
    "p.Entretien": { "name": "blockquote", "classes": ["interview"] },
    # "p.Liste_01": { "name": "", "classes": [] },
    # "p.Liste_02": { "name": "", "classes": [] },
    # "p.Liste_03": { "name": "", "classes": [] },
    # "p.Note": { "name": "", "classes": [] },
    "p.Page_chapitre_Auteur-titre-chapitre": { "name": "h3", "classes": ["author"] },
    "p.Page_chapitre_FRISE_Chapitre": {},
    "p.Page_chapitre_FRISE_Parties": {},
    # "p.Page_chapitre_Infos-texte": { "name": "", "classes": [] },
    "p.Page_chapitre_Sous-titre": { "name": "h2", "classes": ["subtitle"] },
    "p.Page_chapitre_URL-Licence": { "name": "a" },
    "p.Page_chapitre_titre-texte": { "name": "h1", "classes": ["title"] },
    "p.Puce-pagis": {},
    "p.Souschap": { "name": "h3" },
    "p.corps-de-texte-premier": { "name": "div", "classes": ["firstParagraph"] },
    "p.l-gende-photo": { "name": "div", "classes": ["legend"] },
    "p.premi-re-page_Auteur-dans-titre": {},
    "p.premi-re-page_Sous-titre": {},
    "p.premi-re-page_Titre-textes-noir": {},
    "p.premi-re-page_bio": {},
    "span.Alegreay-10-regular": { "name": "span" },
    "span.Alegreay-italic": { "name": "i" },
    "span.Alegreya-italic-7-5": { "name": "i" },
    "span.BIO-Alegreya-Medium-italic-9-8": { "name": "span" },
    "span.BIO-Karla-Extra-Bold": { "name": "span" },
    "span.CHAPITRES-Jambage": { "name": "span" },
    "span.Entretien_Entretien-01": { "name": "b" },
    "span.Entretien_Entretien-02": { "name": "b" },
    "span.FRISE_FRISE_Slash": { "name": "span" },
    "span.FRISE_FRISE_jambage": { "name": "span" },
    "span.FRISE_FRISE_soulignement": { "name": "span" },
    "span.FRISE_Frise_9": { "name": "span" },
    "span.Karla-Reg-7": { "name": "span" },
    "span.Karla-Reg-9-4-COURANT-SEC": { "name": "span" },
    "span.NOTE_num-rotation-dans-note": { "name": "span" },
    "span.NOTE_puce-dans-note": { "name": "span" },
    "span.PAGISChiffre-dans-puce-": {},
    "span.SOUSCHAPITRE-Jambage": { "name": "span" },
    "span.Sous-chapitre": { "name": "span" },
    "span.URL_Slash-pour-note": { "name": "span" },
    "span.URL_URL7_Slash": { "name": "span" },
    "span.URL_URL7_Slash1": { "name": "span" },
    "span.URL_URL_7-avec-jambage": { "name": "span" },
    "span.URL_URL_Slash1_Pages_noires": { "name": "span" },
    "span.URL_URL_Slash_pagesNoires": { "name": "span" },
    "span.URL_URL_pagesNoire": { "name": "span" },
    "span.XXXXX": { "name": "span", "classes": ["siecle"] },
    ".note-rose": { "name": "span" }
}

ID_TO_DELETE = [
    "_idContainer001",
    "_idContainer002",
    "_idContainer003",
    "_idContainer004",
    "_idContainer005",
    "_idContainer006",
    "_idGenObjectLayout",
    # PLE
    # "_idContainer007",
    # "_idContainer008",
    # "_idContainer009",
    # "_idContainer010",
    # "_idContainer011",
    # "_idContainer012",
    # "_idContainer013",
    # "_idContainer014",
    # "_idContainer455",
    # "_idContainer456",
    # "_idContainer457",
    # "_idContainer458",
    # "_idContainer459",
    # "_idContainer460",
    # "_idContainer461",
    # "_idContainer462",
    # "_idContainer463",
    # "_idContainer464",
    # "_idContainer465",
]

FOOTNOTES_CLASS = "Note_de_bas_de_pages" # BOLLO
# FOOTNOTES_CLASS = "nbp" # NN